# #######################################################################################################################
#     ___       __       ___  __
#    / _ |__ __/ /____  / _ \/ /_ _____ _
#   / __ / // / __/ _ \/ ___/ / // / _ `/
#  /_/ |_\_,_/\__/\___/_/  /_/\_,_/\_, /
#                                 /___/ General-Config
# Thank you for using AutoPlug!
# You can find detailed installation instructions at our Spigot post: https://www.spigotmc.org/resources/autoplug-automatic-plugin-updater.78414/
# If there are any questions or you just wanna chat, join our Discord: https://discord.gg/GGNmtCC
# 
# #######################################################################################################################
autoplug-general-config: 
  server: 
    # Enter your server-key here. You get the key by registering on https://autoplug.online.
    # The key is essential to perform most of AutoPlugs main operations and it enables remote access from your account.
    # No matter what, keep this key private to ensure your servers security!
    key: dMklXomL39HvZDqttyQnWioouupgZ3lD6E8M73gtehyvlqWPSTyltd8859tEBcfNidCuCzdX10je45hgVQiKlMV2OBLg5I8K2xaE4IGZl4eie78i7m5tqKWlMvQp7Jpkpv2mZTVZfDDWp4kclvt37Yq1CiBbo5lWaDEeTrqxyh7KFaTPhGDxbnIVMN1TmFCVOSeUMal6Gh5AJgsI1dAQNaecX4hv0PpoPTJVSfjbN5jMFYSv7cKdVf2YTB
    # This is the java version your server will be running on.
    # If you plan to use a specific version of java or you don't have the java path as a System-PATH variable, enter its path here.
    # Otherwise leave it as it is.
    # Example for windows: C:\Progra~1\Java\jdk-14.0.1\bin\java.exe
    java-version: java
    # The auto-find feature will scan through your root directory and find the first jar with another name than AutoPlugLauncher.jar.
    # The auto-find feature will fail if...
    # ... you have more than 2 jars in your root directory.
    # ... your server jar is located in another directory.
    # You can fix this by entering its file path (linux and windows formats are supported)
    # or by entering its file name below, without its .jar file extension (only if AutoPlug is also in the root directory).
    jar: auto-find
    flags: 
      # If you were using java startup flags add them to this list one by one.
      # For flags like - -XX:+UseG1GC (with 2 bars) remove one bar, so it looks like this in the list: - XX:+UseG1GC
      # More on this topic:
      # https://forums.spongepowered.org/t/optimized-startup-flags-for-consistent-garbage-collection/13239
      # https://aikar.co/2018/07/02/tuning-the-jvm-g1gc-garbage-collector-flags-for-minecraft/
      enable: true
      list: 
        - Xms2G
        - Xmx2G
    arguments: 
      # Arguments that are passed after '... -jar server.jar <arguments>' belong here.
      # They can be specific to the server software you are using.
      # More on this topic:
      # https://bukkit.gamepedia.com/CraftBukkit_Command_Line_Arguments
      # https://www.spigotmc.org/wiki/start-up-parameters/?noRedirect=1
      enable: true
      list: nogui
  # Determines the 'before startup tasks' cool-down in minutes. Minimum is 5.
  cool-down: 5
