# #######################################################################################################################
#     ___       __       ___  __
#    / _ |__ __/ /____  / _ \/ /_ _____ _
#   / __ / // / __/ _ \/ ___/ / // / _ `/
#  /_/ |_\_,_/\__/\___/_/  /_/\_,_/\_, /
#                                 /___/ Plugins-Config
# Thank you for using AutoPlug!
# You can find detailed installation instructions at our Spigot post: https://www.spigotmc.org/resources/autoplug-automatic-plugin-updater.78414/
# If there are any questions or you just wanna chat, join our Discord: https://discord.gg/GGNmtCC
# 
# #######################################################################################################################
# This file contains detailed information about your installed plugins. It is fetched from each plugins 'plugin.yml' file (located inside its jar).
# The data gets refreshed before performing an update-check. To exclude a plugin from the check set exclude=true.
# If a name/author/version is missing, the plugin gets excluded automatically.
# You can add extra information by defining an id (spigot or bukkit) and a custom link (optional & must be a static link to the latest plugin jar).
# The spigot-id of a plugin, can be found directly in the url. Example:
# Url: https://www.spigotmc.org/resources/autoplug-automatic-plugin-updater.78414/
# The examples spigot-id is therefore 78414. For the bukkit-id (or project-id) you need to visit the plugins bukkit site and read it from the box at the right.
# If a spigot-id is not given, AutoPlug will try and find the matching id by using its unique search-algorithm (if it successes the spigot-id gets set, else it stays 0).
# If both (bukkit and spigot) ids are provided, the spigot-id will be used.
# The configuration for uninstalled plugins wont be removed from this file, but they are automatically excluded from future checks (the exclude value is ignored).
# If multiple authors are provided, only the first author will be used by the search-algorithm.
# Note: Remember, that the values for exclude, version and author get overwritten if new data is available.
# Note for plugin devs: You can add your spigot/bukkit-id to your plugin.yml file. For more information visit https://autoplug.online/faq
autoplug-plugins-config: 
  general: 
    # Keep the plugins entry in this file even after its removal/uninstallation?
    keep-removed: false