# #######################################################################################################################
#     ___       __       ___  __
#    / _ |__ __/ /____  / _ \/ /_ _____ _
#   / __ / // / __/ _ \/ ___/ / // / _ `/
#  /_/ |_\_,_/\__/\___/_/  /_/\_,_/\_, /
#                                 /___/ Updater-Config
# Thank you for using AutoPlug!
# You can find detailed installation instructions at our Spigot post: https://www.spigotmc.org/resources/autoplug-automatic-plugin-updater.78414/
# If there are any questions or you just wanna chat, join our Discord: https://discord.gg/GGNmtCC
# 
# #######################################################################################################################
# Available profiles for all updaters are: NOTIFY, MANUAL and AUTOMATIC.
# NOTIFY: Only notifies when updates are available.
# MANUAL: Only downloads the updates to /autoplug-downloads.
# AUTOMATIC: Downloads and installs updates automatically.
autoplug-updater-config: 
  self-updater: 
    # Executed before mc server startup.
    # Responsible for updating AutoPlug.
    enable: true
    profile: AUTOMATIC
    # Choose between 'stable' and 'beta' builds.
    # Stable builds are recommended.
    build: stable
  server-updater: 
    # Executed before mc server startup.
    enable: true
    profile: MANUAL
    # Select your favorite server software. Enter the name below.
    # Currently supported:
    # - paper (https://papermc.io/)
    # - waterfall (https://github.com/PaperMC/Waterfall)
    # - travertine (https://github.com/PaperMC/Travertine)
    # Note: If you change this, also reset the "build-id" to 0 to guarantee correct update-detection.
    software: 
    # Currently supported minecraft versions:
    # - paper versions: https://papermc.io/api/v2/projects/paper
    # - waterfall versions: https://papermc.io/api/v2/projects/waterfall
    # - travertine versions: https://papermc.io/api/v2/projects/travertine
    # Note: Only update to a newer version if you are sure that all your essential plugins support that version.
    # Note: Remember that worlds may not be converted to older versions.
    # Note: If you change this, also reset the "build-id" to 0 to guarantee correct update-detection.
    version: 0
    # Each release/update has its unique build-id. First release was 1, the second 2 and so on...
    # If you change your server software or mc-version, remember to change this to 0, to ensure proper update-detection.
    # Otherwise don't touch this. It will get incremented after every successful update automatically.
    build-id: 0
  plugins-updater: 
    # Executed before mc server startup.
    enable: true
    profile: MANUAL
