# #######################################################################################################################
#     ___       __       ___  __
#    / _ |__ __/ /____  / _ \/ /_ _____ _
#   / __ / // / __/ _ \/ ___/ / // / _ `/
#  /_/ |_\_,_/\__/\___/_/  /_/\_,_/\_, /
#                                 /___/ Tasks-Config
# Thank you for using AutoPlug!
# You can find detailed installation instructions at our Spigot post: https://www.spigotmc.org/resources/autoplug-automatic-plugin-updater.78414/
# If there are any questions or you just wanna chat, join our Discord: https://discord.gg/GGNmtCC
# 
# #######################################################################################################################
autoplug-tasks-config: 
  live-tasks: 
    # Enable this to view the detailed progress of a task. Currently only works for windows.
    # Enabling this on unsupported OS will result in console spam.
    enable: false
    # How often a task should get refreshed and update its information. 250 milliseconds are recommended.
    refresh-interval: 250
