# #######################################################################################################################
#     ___       __       ___  __
#    / _ |__ __/ /____  / _ \/ /_ _____ _
#   / __ / // / __/ _ \/ ___/ / // / _ `/
#  /_/ |_\_,_/\__/\___/_/  /_/\_,_/\_, /
#                                 /___/ Plugins-Config
# Thank you for using AutoPlug!
# You can find detailed installation instructions at our Spigot post: https://www.spigotmc.org/resources/autoplug-automatic-plugin-updater.78414/
# If there are any questions or you just wanna chat, join our Discord: https://discord.gg/GGNmtCC
# 
# #######################################################################################################################
# This file contains detailed information about your installed plugins. It is fetched from each plugins 'plugin.yml' file (located inside its jar).
# The data gets refreshed before performing an update-check. To exclude a plugin from the check set exclude=true.
# If a name/author/version is missing, the plugin gets excluded automatically.
# You can add extra information by defining an id (spigot or bukkit) and a custom link (optional & must be a static link to the latest plugin jar).
# The spigot-id of a plugin, can be found directly in the url. Example:
# Url: https://www.spigotmc.org/resources/autoplug-automatic-plugin-updater.78414/
# The examples spigot-id is therefore 78414. For the bukkit-id (or project-id) you need to visit the plugins bukkit site and read it from the box at the right.
# If a spigot-id is not given, AutoPlug will try and find the matching id by using its unique search-algorithm (if it successes the spigot-id gets set, else it stays 0).
# If both (bukkit and spigot) ids are provided, the spigot-id will be used.
# The configuration for uninstalled plugins wont be removed from this file, but they are automatically excluded from future checks (the exclude value is ignored).
# If multiple authors are provided, only the first author will be used by the search-algorithm.
# Note: Remember, that the values for exclude, version and author get overwritten if new data is available.
# Note for plugin devs: You can add your spigot/bukkit-id to your plugin.yml file. For more information visit https://autoplug.online/faq
autoplug-plugins-config: 
  general: 
    # Keep the plugins entry in this file even after its removal/uninstallation?
    keep-removed: false
  MoveMeNow: 
    exclude: false
    version: 1.2-CUSTOMBUILD
    latest-version: 1.2-17
    author: roblabla
    spigot-id: 17
    bukkit-id: 0
    c-link: 
  floodgate-bungee: 
    exclude: false
    version: 1.0-SNAPSHOT
    latest-version: 
    author: GeyserMC
    spigot-id: 0
    bukkit-id: 0
    c-link: https://ci.opencollab.dev/job/GeyserMC/job/Floodgate/job/master/lastSuccessfulBuild/artifact/bungee/target/floodgate-bungee.jar
  EasyBackup: 
    exclude: false
    version: 3.3.4
    latest-version: 
    author: Forseth11
    spigot-id: 0
    bukkit-id: 0
    c-link: 
  ServerListPlus: 
    exclude: false
    version: '3.4.8'
    latest-version: 
    author: 'Minecrell <https://github.com/Minecrell>'
    spigot-id: 0
    bukkit-id: 0
    c-link: 
  OpenAudioMc: 
    exclude: false
    version: 6.4
    latest-version: 6.5
    author: Mindgamesnl
    spigot-id: 30691
    bukkit-id: 0
    c-link: 
  BungeeAnnounce: 
    exclude: false
    version: 7.0
    latest-version: 
    author: Asynchronous
    spigot-id: 0
    bukkit-id: 0
    c-link: 
  AACBungeeConnectSpigot: 
    exclude: false
    version: 1.6.6
    latest-version: 
    author: Nojo | Noah
    spigot-id: 0
    bukkit-id: 0
    c-link: 
  Votifier: 
    exclude: false
    version: 2.7.1
    latest-version: 
    author: Ichbinjoe
    spigot-id: 0
    bukkit-id: 0
    c-link: 
  SkinsRestorer: 
    exclude: false
    version: 13.8.8
    latest-version: 
    author: Th3Tr0LLeR
    spigot-id: 0
    bukkit-id: 0
    c-link: 
  LuckPerms: 
    exclude: false
    version: 5.2.118
    latest-version: 5.2.76
    author: Luck
    spigot-id: 28140
    bukkit-id: 0
    c-link: 
  BungeeStaffChat: 
    exclude: false
    version: 2.0-SNAPSHOT
    latest-version: 
    author: Wout Ceulemans
    spigot-id: 0
    bukkit-id: 0
    c-link: 
  ExploitFixer: 
    exclude: false
    version: 1.5.2
    latest-version: 
    author: 2LS
    spigot-id: 0
    bukkit-id: 0
    c-link: 
  BungeeGuard: 
    exclude: true
    version: 1.0-SNAPSHOT
    latest-version: 
    author: 
    spigot-id: 0
    bukkit-id: 0
    c-link: 
  ProtocolChanger: 
    exclude: false
    version: 1.0.0
    latest-version: 
    author: SimplyRin
    spigot-id: 0
    bukkit-id: 0
    c-link: 
  BungeeTabListPlus: 
    exclude: false
    version: 3.4.1
    latest-version: 3.4.3
    author: CodeCrafter47
    spigot-id: 313
    bukkit-id: 0
    c-link: 
  AACBungeeCord: 
    exclude: false
    version: 1.0
    latest-version: 
    author: Wolfiediamond
    spigot-id: 0
    bukkit-id: 0
    c-link: 
  CraftingStore: 
    exclude: false
    version: 2.2.0
    latest-version: 2.6.2
    author: Tim_kwakman
    spigot-id: 31331
    bukkit-id: 0
    c-link: 
  SlashServer: 
    exclude: false
    version: 3
    latest-version: 
    author: Bloodsplat
    spigot-id: 0
    bukkit-id: 0
    c-link: 
